* About
This is a place for me to learn postgreSQL. The main idea is
that given a table of recipes and ingredients I should be able to
  1. Be able to output cooking instructions for a recipe
  2. Make a weekly shopping list
  3. Calculate calories per meal
  4. See which recipes work best with ingredients in my pantry and
  5. Approximate the cost of the shopping list

* What's coming next?
Given that the database is partially filled, I need a way to
interact with it in a more reasonable way. This can be
broken into two main blocks of work:

1. Have a script which walks the user through adding
   ingredients to a new recipe.

2. Write functions for each of the queries in the .sql file
   so that they're accessible from anywhere.
   
It would be nice to have a fully featured UI, but that's
outside of the scope of the project at the moment.

** What's been fixed?
  + Build the database from a csv
  + Changed recipe_id, ingredient_id -> id
  + Switch to "in" instead of conditional
  + Indexed names
  + Sort "pantry search" by a count
  + Names are unique



